# Generated by Django 5.2 on 2025-04-28 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Введите корректное имя пользователя. Разрешены буквы, цифры и @/./+/-/_.",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Юзернейм",
            ),
        ),
    ]
