# Generated by Django 5.2 on 2025-04-28 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Введите корректное имя пользователя. Разрешены буквы, цифры и @/./+/-/_.",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Юзернейм",
            ),
            preserve_default=False,
        ),
    ]
