# Generated by Django 5.2 on 2025-04-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients_in_recipe",
                to="api.ingredient",
                verbose_name="Продукт",
            ),
        ),
    ]
