# Generated by Django 5.2 on 2025-04-30 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_ingredientinrecipe_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="ingredientinrecipe",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="ingredientinrecipe",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="author",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[\\w.@+-]+$")
                ],
                verbose_name="Юзернейм",
            ),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="IngredientInRecipe",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="ShoppingCart",
        ),
    ]
